### ISSUE TITLE
(Linux) Lowercase group/user names and replace spaces with ^

### ISSUE THREAD

**Issue by lorengordon** [plus3it/join-domain-formula#71]
Would help reduce errors when using the admin/login user/group options.

**Comment by ferricoxide** [comment]
Remember that we'd decided not to do this "solution-wide" because `^` is specific to PBIS.  The formula was supposed to be accomodate more than just PBIS (esp. since EL7's native tool - SSSD - could supplant PBIS for that platform and other tenants are/were using things like Centrify and Quest).

**Comment by lorengordon** [comment]
Well, we can either ditch the multi-mechanism concept, since that's gone nowhere in over a year (and we can always add it back when/if it's time does come), or we can implement this in a way that is specific to PBIS. Neither is particularly difficult. I lean towards the former because I don't like clutter sitting around in these projects.

**Comment by ferricoxide** [comment]
PBIS was originally selected because the native handler for EL5 and EL6 was `winbind`. Particularly in EL5, `winbind` was of a vintage that didn't well-handle a domain the size/complexity of the main production domain, nor (especially) did it handle the NTLM sign and seal very well. That said, because of the size/complexity of the main production domain, the PBIS community edition logs a crap-ton of errors due to the much, much smaller mapped uid/gid namespace it uses. So, overall, I'd prefer to keep the modular functionality because I'd like to pursue native (sssd) on EL7 if it's able to handle a domain the size of the main production domain. 

As constructed, the Linux half of the formula uses a pillar to select the authentication module used. Our default pillars for the join-domain-formula currently selects pbis.

It should be easy enough to extend the top-level PBIS handler to do an upper2lower and convert spaces to ^s before passing tokens on to the other handlers. Doing these mods within the top-level pbis-script should avoid having to alter anything outside of the PBIS component-tree or even lower down in the component-tree.

**Comment by lorengordon** [comment]
euw, no, not doing it that way, but fine, we can leave the clutter. :p

**Comment by ferricoxide** [comment]
Just saying that it makes more sense to do the `^` handling within the PBIS context since other connectors use different tokens (e.g., Centrify uses `+`; SSSD leaves spaces "as is").

The case-normalization can probably happen above the connector level since Linux generally prefers POSIX-style case (i.e., "all lower" or simply ignores case).

**Comment by lorengordon** [comment]
I think this one is pretty doable, even handling it in the connector logic.
